/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Parametrizador',
      className: 'sb-cat',
      collapsed: false,
      link: { type: 'doc', id: 'parametrizador/pagina-inicial' },
      items: [{ type: 'autogenerated', dirName: 'parametrizador' }],
    },
  ],
};
module.exports = sidebars;
